# Generated by Django 3.2.20 on 2023-07-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_auto_20230722_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='start_date',
        ),
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='week_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
