# Generated by Django 3.2.20 on 2023-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_auto_20230722_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
