# Generated by Django 3.2.20 on 2023-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_booked_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='comment',
            field=models.TextField(),
        ),
    ]
