# Generated by Django 3.2.20 on 2023-07-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_auto_20230723_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='week_number',
        ),
        migrations.AlterField(
            model_name='booked',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
